HIT = "Hit"
STAND = "Stand"
START_OVER = "Start a new game"
GET_MATH = "Get math"

PENDING = "Pending"
BLACKJACK = "Blackjack"
BUSTED = "Busted"
STOOD = "Stood"
DEAL_NEXT_HAND = "Deal next hand"
CONTINUE = "Continue"
